# Generated by Django 3.2.6 on 2021-08-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=500)),
                ('unit_number', models.IntegerField()),
                ('room_description', models.CharField(max_length=500)),
                ('size', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_sold', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('property_type', models.CharField(max_length=500)),
                ('price', models.PositiveBigIntegerField()),
                ('price_per_sqft', models.PositiveBigIntegerField()),
                ('built_up_area', models.PositiveBigIntegerField()),
                ('bed', models.CharField(max_length=200)),
            ],
        ),
    ]
