# Generated by Django 3.2.6 on 2021-08-12 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildingdetails',
            old_name='size',
            new_name='sizes',
        ),
        migrations.RenameField(
            model_name='buildingdetails',
            old_name='type',
            new_name='types',
        ),
    ]
