# Generated by Django 3.2.6 on 2021-08-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_app', '0002_auto_20210812_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydata',
            name='built_up_area',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propertydata',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propertydata',
            name='price_per_sqft',
            field=models.CharField(max_length=100),
        ),
    ]
