# Generated by Django 3.2.6 on 2021-08-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_app', '0003_auto_20210812_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=500, null=True)),
                ('first_name', models.CharField(blank=True, max_length=500, null=True)),
                ('last_name', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=500, null=True)),
                ('broker_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('dateof_issuance_of_brokercard', models.CharField(blank=True, max_length=200, null=True)),
                ('brn', models.IntegerField()),
                ('name_of_the_establishment', models.CharField(blank=True, max_length=500, null=True)),
                ('office_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('orn', models.IntegerField(blank=True, null=True)),
                ('office_address', models.CharField(blank=True, max_length=700, null=True)),
                ('dec_lisc', models.IntegerField(blank=True, null=True)),
                ('agent_photo', models.ImageField(blank=True, null=True, upload_to='agent_photo/%Y/%m/%d/')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logo/%Y/%m/%d/')),
                ('area_specialist', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
