# Generated by Django 3.2.6 on 2021-08-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_app', '0004_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
