# Generated by Django 3.2.6 on 2021-08-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_app', '0005_signup_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='agent_photo',
            field=models.ImageField(default='03.jpg', upload_to='agent_photo/'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='company_logo',
            field=models.ImageField(default='03.jpg', upload_to='company_logo/'),
        ),
    ]
