# Generated by Django 3.2.6 on 2021-08-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_app', '0006_auto_20210818_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
