# Generated by Django 3.2.6 on 2021-08-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_app', '0007_auto_20210820_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='agent_photo',
            field=models.ImageField(blank=True, default='03.jpg', null=True, upload_to='agent_photo/'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='company_logo',
            field=models.ImageField(blank=True, default='03.jpg', null=True, upload_to='company_logo/'),
        ),
    ]
